name: Delete Monitoring Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to remove monitoring'
        required: true
        default: 'dev'

jobs:
  teardown-monitoring:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      CLUSTER_NAME: zh-test-dev-eks-cluster  # Existing cluster
      MONITORING_NAMESPACE: monitoring

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --name "$CLUSTER_NAME" \
            --region "$AWS_REGION"

      - name: Uninstall Prometheus
        run: |
          helm uninstall prometheus -n $MONITORING_NAMESPACE || echo "Prometheus release not found"

      - name: Uninstall Grafana
        run: |
          helm uninstall grafana -n $MONITORING_NAMESPACE || echo "Grafana release not found"

      - name: Delete EBS StorageClass
        run: |
          kubectl delete -f monitoring/gp3-immediate.yaml --ignore-not-found

      - name: Delete Monitoring Namespace
        run: |
          kubectl delete namespace $MONITORING_NAMESPACE --ignore-not-found
