name: Deploy Prometheus

on:
  push:
    branches:
      - main

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    env:
      TF_STATE_BUCKET: sctp-ce10-tfstate
      TF_STATE_KEY: zh-test/eks.tfstate
      TF_REGION: ap-southeast-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="key=${TF_STATE_KEY}" \
            -backend-config="region=${TF_REGION}"

      - name: Fetch EKS cluster outputs
        id: tf-output
        run: |
          # Fetch cluster_name safely using JSON
          CLUSTER_NAME=$(terraform output -json cluster_name | tr -d '"')
          
          if [ -z "$CLUSTER_NAME" ]; then
            echo "Error: cluster_name output is empty"
            exit 1
          fi

          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region $TF_REGION

      - name: Deploy Monitoring Stack
        run: |
          kubectl apply -f monitoring/
