name: Deploy Prometheus

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      CLUSTER_NAME: zh-test-dev-eks-cluster   # Need to change this to group cluster name/env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region $AWS_REGION

      - name: Deploy Monitoring Stack
        run: |
          kubectl apply -f monitoring/