name: Deploy Monitoring Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy monitoring'
        required: true
        default: 'dev'
jobs:
  verify-monitoring:
    runs-on: ubuntu-latest
    env:
      MONITORING_NAMESPACE: monitoring
      TARGET_NAMESPACES: myApp-dev,myApp-uat

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Apply Namespace & StorageClass
        run: |
          kubectl apply -f gp3-storageclass.yaml  #Tor wei have k8, use that
          kubectl apply -f monitoring-namespace.yaml

      - name: Install kube-prometheus-stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

          helm upgrade --install monitoring-stack prometheus-community/kube-prometheus-stack \
            --namespace ${{ env.MONITORING_NAMESPACE }} \
            --create-namespace \
            --values ./monitoring-values.yaml