apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: myApp-dev   # match deployment namespace
  labels:
    app: flaskapp
spec:
  selector:
    app: flaskapp
  ports:
    - name: http-metrics
      port: 5000
      targetPort: 5000
